export default { 
  'request.error': 'Falha na solicitação', 
  // cycle_text 
  'cycle.month_price': 'Mensal', 
  'cycle.quarter_price': 'Trimestral', 
  'cycle.half_year_price': 'Semestralmente', 
  ' cycle.year_price ':' Anualmente ', 
  ' cycle.two_year_price ':' Bienalmente ', 
  ' cycle.three_year_price ':' Triennially ', 
  ' cycle.onetime_price ':' One Time ', 
  ' cycle.reset_price ':' Data Reset Package ', 
  // order_status 
  ' order_status.no_paid ':' Pagamento pendente ', 
  ' order_status.opening ':' Pendente ativo ', 
  ' order_status.cancel ':' Cancelado ', 
  ' order_status.done ':' Concluído ', 
  ' order_status.surplus ':' Convertido ',
  // Commission_status 
  'Commission_status.pending_confirm': 'Pendente', 
  'Commission_status.confirm': 'Confirmando', 
  'Commission_status.done': 'Concluído', 
  'Commission_status.reject': 'Inválido', 
  // cabeçalho 
  'header.user_center ':' Central do usuário ', 
  ' header.logout ':' Logout ', 
  ' header.search ':' Pesquisar ', 
  // nav 
  ' nav.dashboard ':' Painel ', 
  ' nav.subscribe ':' Assinatura ', 
  'nav.my_subscribe': 'Minha assinatura', 
  'nav.buy_subscribe': 'Comprar assinatura', 
  'nav.bill': 'Faturamento',
  'nav.my_order': 'Meus pedidos', 
  'nav.my_invite': 'Meu convite', 
  'nav.user': 'Conta',
  'nav.user_center': 'User Center', 
  'nav.my_ticket': 'My Tickets', 
  'nav.traffic_detail': 'Transfer Data Details', 
  'nav.knowledge': 'Knowledge Base', 
  // dashboard 
  'dashboard .not_bind_telegram ':' Ainda sem link para Telegram ', 
  ' dashboard.click_here_bind ':' Clique aqui para criar um link para Telegram ', 
  ' dashboard.announcement ':' Anúncios ', 
  ' dashboard.override ':' Visão geral ', 
  ' painel .pending_order ':' Pedidos pendentes ', 
  ' dashboard.pending_ticket ':' Tickets pendentes ', 
  ' dashboard.my_invite ':' Meu convite ', 
  ' painel.my_subscribe ':' Minha assinatura ', 
  ' dashboard.add_subscribe ':' Solicitar uma assinatura ',
  'dashboard.not_expire': 'A assinatura é válida por tempo ilimitado', 
  'dashboard.expired': 'Expirado', 
  'dashboard.subscribe_info': 'Expirará em {data}, {dia} dias antes da expiração, após {reset_day } dias redefinir dados de transferência ', 
  ' dashboard.traffic_info ':' {used} Usado / Total {total} ', 
  ' dashboard.view_subscribe ':' Ver Assinatura ', 
  ' dashboard.renew ':' Renovar ', 
  // esquecerPassword 
  ' ForgotPassword.email ':' Email ', 
  ' forgetPassword.email_verify_code ':' Código de verificação de email ', 
  ' forgetPassword.send ':' Send ', 
  ' forgetPassword.password ':' Password ',
  'forgetPassword.reset_password': 'Reset Password', 
  'forgetPassword.back_login': 'Voltar para Login',
  // convide 
  'invite.table_code': 'Código de convite', 
  'invite.table_create_time': 'Hora de criação', 
  'invite.table_action': 'Action', 
  'invite.copy_link': 'Copy Link', 
  'invite.table_complete_time ':' Tempo completo ', 
  ' invite.table_commission_balance ':' Comissão ', 
  ' invite.table_commission_status ':' Status da comissão ', 
  ' invite.override ':' Visão geral do convite ', 
  ' invite.register_count ':' Usuários registrados ', 
  'invite.commission_rate': 'Taxa de comissão', 
  'invite.confirm_commission': 'Comissão pendente', 
  'convite.confirm_commission_tip ':' A comissão chegará à sua conta de comissão após revisão. ',
  'invite.invite_code_manage': 'Gerenciamento do código de convite', 
  'invite.generate_code': 'Gerar o código do convite', 
  'invite.detail': 'Detalhes do convite', 
  'invite.copy_success': 'Copiado com sucesso', 
  // login 
  ' login.email ':' Email ', 
  ' login.password ':' Senha ', 
  ' login ':' Login ', 
  ' login.register ':' Registrar ', 
  ' login.forget_password ':' Esqueci a senha ', 
  // pedido 
  'order.table_no': 'Número do pedido #', 
  'order.table_cycle': 'Tipo / Ciclo', 
  'order.table_amount': 'Valor do pedido',
  'order.table_status': 'Status do pedido', 
  'order.table_create_time': 'Hora de criação', 
  'order.table_action': 'Ação',
  'order.view_detail': 'Ver detalhes', 
  'order.cancel': 'Cancelar', 
  'order.order_manage': 'Gerenciamento de pedidos', 
  'order.please_select_pay_method': 'Selecione um método de pagamento', 
  'order.please_check_credit_card ':' Verifique as informações de pagamento com cartão de crédito ', 
  ' order.order_detail ':' Detalhes do pedido ', 
  ' order.product ':' Product ', 
  ' order.type_cycle ':' Type / Cycle ', 
  ' order.amount ': 'Amount', 
  'order.traffic': 'Transfer Data', 
  'order.discount': 'Discount', 
  'order.surplus': 'Converted', 
  'order.reembolso ':' Reembolso ', 
  ' pedido.balance_pay ':' Pague com saldo ', 
  ' pedido.pay_method ':' Método de pagamento ',
  'order.enter_credit_info': 'Preencha as informações de pagamento com cartão de crédito', 
  'order.credit_alert': 'Não coletaremos as informações do seu cartão de crédito, número do cartão de crédito e outros detalhes para usar apenas para verificar a transação atual.', 
  'pedido. total_amount ':' Order Total ', 
  ' order.total ':' Total ', 
  ' order.checkout ':' Checkout ', 
  ' order.waiting_payment ':' Waiting for payment ', 
  ' order.result_opening_title ':' Abrindo ', 
  'order.result_opening_sub_title': 'O sistema de pedidos está processando, aguarde 1-3 minutos.', 
  'order.result_cancel_title': 'Cancelado', 
  'order.result_cancel_sub_title': 'O pedido foi cancelado devido ao pagamento de horas extras. ', 
  ' Order.result_success_title ':' Sucesso ',
  'order.result_success_sub_title': 'O pedido foi pago e aberto.', 
  // plan 
  'plan.select_subscribe': 'Selecione uma assinatura', 
  'plan.buy': 'Assine agora', 
  'plan.setting_subscribe': ' Configurar assinatura ', 
  ' plan.discount ':' Desconto ', 
  ' plan.cycle ':' Ciclo de pagamento ', 
  ' plan.have_coupon ':' Tem cupons? ', 
  ' Plan.coupon_verify ':' Verificar ', 
  ' plano. order_total_amount ':' Order Total ', 
  ' plan.place_order ':' Order ', 
  ' plan.total ':' Total ', 
  ' plan.subscribe_change_title ':' Atenção alterações de assinatura ',
  'plan.subscribe_change_content': 'Atenção, por favor, alterar a assinatura irá sobrescrever a sua assinatura atual.',
  'plan.subscribe_not_renew': 'Esta assinatura não pode ser renovada', 
  'plan.choose_another_subscribe': 'Escolha outra assinatura', 
  // perfil 
  'profile.user_center': 'Central do usuário', 
  'profile.my_wallet': 'Minha carteira' , 
  'profile.balance_tip': 'Saldo da conta (apenas para faturamento)', 
  'profile.commission_balance_tip': 'Comissão de convite (pode ser usada para sacar)', 
  'profile.wallet_component': 'Detalhes da carteira', 
  'profile.transfer ':' Transferir ', 
  ' profile.commission_withdraw ':' Retirada de comissão de convite ', 
  ' profile.change_password ':' Alterar senha ',
  'profile.save': 'Salvar', 
  'profile.old_password': 'Senha Antiga',
  'profile.new_password': 'New Password', 
  'profile.re_new_password': 'New Password', 
  'profile.please_enter_old_password': 'Por favor, digite a senha antiga', 
  'profile.please_enter_new_password': 'Por favor, digite a nova senha', 
  'profile.please_enter_re_new_password': 'Digite a nova senha novamente', 
  'profile.notice': 'Notificação', 
  'profile.expire_remind': 'Lembrete de e-mail de expiração de assinatura', 
  'profile.traffic_remind': 'Alerta de e-mail de transferência insuficiente ', 
  ' profile.bind_telegram ':' Link para Telegram ', 
  ' profile.start ':' Comece agora ', 
  ' profile.reset_subscribe ':' Redefinir assinatura ', 
  ' profile.reset ':' Redefinir ',
  'profile.reset_info_notify_title': 'Deseja redefinir a assinatura?', 
  'profile.reset_info_notify_content': 'No caso de informações da conta ou vazamento de assinatura, esta opção é usada para redefinir seu UUID e a assinatura será alterada após redefinir, você precisa para se inscrever novamente. ', 
  ' profile.reset_info_notify_success ':' Redefinir com sucesso ', 
  ' profile.two_password_error ':' Duas novas senhas inseridas não correspondem ', 
  // reg 
  ' register.two_password_error ':' As senhas inseridas não correspondem ', 
  ' register.email ':' Email ', 
  ' register.verify_code ':' Código de verificação de e-mail ', 
  ' register.password ':' Password ', 
  'register.re_password ':' Password ', 
  ' register.send ':' Send ',
  'register.invite_code_require': 'Código de convite', 
  'register.invite_code': 'Código de convite (opcional)', 
  'register': 'Register', 
  'register.back_login': 'Voltar ao Login', 
  'register.tos_url' : 'Li e concordo com os <a target="_blank" href="{url}"> termos de serviço </a>', 
  'register.please_agree_tos': 'Concordo com os termos de serviço', 
  / / subscribe 
  'subscribe.table_name': 'Nome', 
  'subscribe.table_tag': 'Tags', 
  'subscribe.table_action': 'Ação', 
  'subscribe.table_status': 'Status', 
  'inscrever-se.table_status_tip ':' Status online do Ponto de Acesso nos últimos 5 minutos ', 
  ' subscribe.table_rate ':' Taxa ',
  'subscribe.table_rate_tip': 'Os dados de transferência usados ​​são multiplicados pela taxa de transferência de dados deduzida', 
  'subscribe.more_action': 'Action', 
  'subscribe.copy_success': 'Copiado com sucesso', 
  'subscribe.copy_link': 'Copiar Link ', 
  ' subscribe.my_subscribe ':' Minha assinatura ', 
  ' subscribe.add_subscribe ':' Solicitar uma assinatura ', 
  ' subscribe.not_expire ':' A assinatura é válida por tempo ilimitado ', 
  ' subscribe.expired ':' Expirado ', 
  ' subscribe.subscribe_info ':' Expirará em {date}, {day} dias antes da expiração, após {reset_day} dias redefinir dados de transferência ', 
  ' subscribe.traffic_info ':'{used} Usado / Total {total} ', 
  ' subscribe.renew ':' Renew ', 
  ' subscribe.action ':' Action ',
  'subscribe.reset_traffic': 'Redefinir dados de transferência atuais', 
  'subscribe.reset_info': 'Redefinir assinatura', 
  'subscribe.node_status': 'Status do ponto de acesso', 
  'subscribe.no_node': 'Nenhum ponto de acesso disponível, se você não subscreveu uma subscrição ou a subscrição expirou, por favor ', 
  ' subscribe.no_node_renew ':' Renovar ', 
  ' subscribe.no_node_go ':' Subscrever ', 
  ' subscribe.reset_traffic_notify_title ':' Tem a certeza que pretende reiniciar o mês actual \ 's transfer data?', 
  'subscribe.reset_traffic_notify_content': 'Clique em "Confirmar" e você será redirecionado para a página de pagamento. Depois que o pedido for pago,
  'subscribe.reset_traffic_notify_cancel': 'Cancelar', 
  'subscribe.reset_info_notify_title': 'Tem certeza que deseja redefinir a assinatura?', 
  'subscribe.reset_info_notify_content': 'Em caso de vazamento de informações da conta ou de sua assinatura, esta opção é usada para redefinir seu UUID e a assinatura será alterada após a redefinição, você precisa se inscrever novamente. ', 
  ' subscribe.reset_info_notify_success ':' Redefinir com sucesso ', 
  // ticket 
  ' ticket.low ':' Baixo ', 
  ' ticket.middle ':' Médio ' , 
  'ticket.high': 'Alto', 
  'ticket.table_subject': 'Assunto', 
  'ticket.table_level': 'Prioridade do tíquete', 
  'tíquete.table_status ':' Status do ticket ', 
  ' ticket.table_create_time ':' Hora de criação ',
  'ticket.table_last_reply': 'Última resposta', 
  'ticket.table_action': 'Ação', 
  'ticket.status_closed': 'Fechado', 
  'ticket.status_pending': 'Resposta pendente', 
  'ticket.status_reply': 'Respondido ', 
  ' ticket.action_view ':' View ', 
  ' ticket.action_close ':' Close ', 
  ' ticket.my_ticket ':' My Tickets ', 
  ' ticket.new_ticket ':' New Ticket ', 
  ' ticket.new_ticket_modal_title ': 'Novo Ticket', 
  'ticket.new_ticket_modal_confirm': 'Confirmar', 
  'ticket.new_ticket.modal_cancel': 'Cancelar', 
  'ticket.subject': 'Assunto',
  'ticket.please_enter_subject': 'Por favor, insira um assunto', 
  'ticket.level': 'Prioridade do tíquete',
  'ticket.please_select_level': 'Selecione a prioridade do ticket', 
  'ticket.message': 'Message', 
  'ticket.please_enter_issue': 'Descreva o problema que você encontrou', 
  // tráfego 
  'traffic.table_record_time': 'Registro Tempo ', 
  ' traffic.table_tx ':' Upload real ', 
  ' traffic.table_rx ':' Download real ', 
  ' traffic.table_rate ':' Taxa de dedução ', 
  ' traffic.table_total ':' Total ', 
  ' traffic.table_total_tip ':' Fórmula: (Upload real + Download real) x Taxa de dedução = Dedução dos dados de transferência ', 
  ' traffic.traffic_detail ':' Detalhes dos dados de transferência ', 
  'traffic.today ':' Today ', 
  ' traffic.month ':' Month ', 
  ' traffic.week ':' Week ',
  // one_click_subscribe 
  'one_click_subscribe.copy_success': 'Copiado com sucesso', 
  'one_click_subscribe.copy_subscribe_url': 'Copiar URL de 
  inscrição' , 'one_click_subscribe.import': 'Exportar para', 
  'one_click_subscribe': 'Quick Subscription', 
  'one_click_subscribe ':' Copiar URL de assinatura ', 
  // transfer_modal 
  ' transfer_modal.title ':' Transferir comissão de convite para saldo da conta ', 
  ' transfer_modal.confirm ':' Confirmar ', 
  ' transfer_modal.cancel ':' Cancelar ', 
  ' transfer_modal.alert ':' O saldo transferido só será usado para o pagamento de {título} ', 
  'transfer_modal.commission_balance ':' Saldo do convite atual ',
  'transfer_modal.transfer_balance': 'Valor da transferência', 
  'transfer_modal.please_enter_transfer_balance': 'Por favor, digite o valor a ser transferido para o saldo', 
  // chat 
  'chat.please_enter_message': 'Por favor, digite para responder ao tíquete ... ', 
  // Draw_modal'draw_modal.title 
  ': 'Solicitar Retirada', 
  'Retirar_modal.confirm': 'Confirmar', 
  'Retirar_modal.cancel': 'Cancelar', 
  'Retirar_modal.withdraw_method': 'Método de Retirada', 
  'Retirar_modal .please_select_method ':' Selecione um método de saque ', 
  ' draw_modal.withdraw_account ':' Conta de saque ',
  ' 
  draw_modal.please_enter_account ':' Por favor, insira a conta de retirada ', // bind_telegram
  'bind_telegram_modal.confirm': 'Entendi', 
  'bind_telegram_modal.title': 'Link para o telegrama', 
  'bind_telegram_modal.step_1': 'Primeira etapa', 
  'bind_telegram_modal.step_2': 'Segunda etapa', 
  'bind_telegram_modal.step_1 ': 'Primeira etapa', 'bind_telegram_modal.step_2': 'Segunda etapa', 'bind_telegram_modal.step_1' ':' Abrir Telegrama e Pesquisar ', 
  ' bind_telegram_modal.send_bot_message ':' Enviar o seguinte comando para o bot ', 
  // conhecimento 
  ' conhecimento ':' Base de Conhecimento ', 
  ' Conhecimento.last_release_date ':' Última Atualização: {data} ' , 
  'knowledge.copy_success': 'Cópia bem sucedida' 
}
